id: IAA3D5322
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-31T05:11:41.483876'
last_modified: '2022-05-31T05:11:41.483901'
parser: null
source_metadata:
  title: Marpa Lotsāwa Series
  language: bo
  description: 'Texts by and about the great Marpa Chökyi Lodrö (mar pa chos kyi blo
    gros, c.1012–1097), renowned as the founder of the Marpa Kagyü tradition and teacher
    of Milarepa:'
  volume:
    fCC8D:
      title: A Combined Guru Yoga for Marpa, Mila, and Gampopa
      base_file: fCC8D.txt
      order: 1
      parent: Guru Yoga
    f2193:
      title: 'A Drop of Sunshine: A Guru Yoga for Lord Marpa'
      base_file: f2193.txt
      order: 2
      parent: Guru Yoga
    f8173:
      title: Guru Yoga of Lord Marpa Lotsāwa
      base_file: f8173.txt
      order: 3
      parent: Guru Yoga
    f9B38:
      title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the
        Three Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
      base_file: f9B38.txt
      order: 4
      parent: Guru Yoga
    fAE11:
      title: Prayer to Lord Marpa, Consort and Heirs
      base_file: fAE11.txt
      order: 5
      parent: Prayers
    f936C:
      title: 'Song of Devotion: A Prayer to Lord Marpa Lotsāwa'
      base_file: f936C.txt
      order: 6
      parent: Prayers
    fA59D:
      title: 'The Melody of Complete Accomplishment: A Prayer to Those Praised as
        Ornaments of the Practice Lineage'
      base_file: fA59D.txt
      order: 7
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
